const div = document.createElement('div');
const h1 = document.createElement('h1');
const form = document.createElement('form');
div.classList.add('wrapper');
document.body.appendChild(div);
h1.textContent = 'Drag and Drop';
h1.classList.add('h1');
form.classList.add('form');
div.appendChild(h1);
div.appendChild(form);
const h2 = document.createElement('h2');
h2.classList.add('h2');
h2.textContent = 'Перетащите сюда файлы';
form.appendChild(h2);
const p = document.createElement('p');
p.textContent = 'или';
form.appendChild(p);
const label = document.createElement('label');
label.classList.add('label');
form.appendChild(label);
const span = document.createElement('span');
span.textContent = 'Загрузите файлы';
label.appendChild(span);
const input = document.createElement('input');
label.appendChild(input);
input.type = 'file';
input.multiple = 'true';
input.accept = '.jpg, .jpeg, .png';
input.classList.add('input');
